# Generated by Django 5.0.1 on 2025-07-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.FloatField(blank=True, null=True)),
                ('working_memory', models.FloatField(blank=True, null=True)),
                ('attention_control', models.FloatField(blank=True, null=True)),
                ('decision_speed', models.FloatField(blank=True, null=True)),
                ('learning_agility', models.FloatField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trait_profile', to='games.gamesession')),
            ],
        ),
    ]
