# Generated by Django 5.0.1 on 2025-07-28 18:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralsession',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Duration of the session in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='behavioralsession',
            name='game_type',
            field=models.CharField(choices=[('balloon_risk', 'Balloon Risk Game'), ('memory_cards', 'Memory Cards Game'), ('reaction_timer', 'Reaction Timer Game'), ('mixed', 'Multiple Games')], default='mixed', help_text='Type of game(s) in this session', max_length=32),
        ),
        migrations.AddField(
            model_name='behavioralsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the session was actually started by the user', null=True),
        ),
        migrations.AddField(
            model_name='behavioralsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='behavioralsession',
            name='session_end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='behavioralsession',
            name='session_start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='behavioralsession',
            index=models.Index(fields=['status'], name='behavioral__status_cd1de7_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralsession',
            index=models.Index(fields=['game_type'], name='behavioral__game_ty_6a093b_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralsession',
            index=models.Index(fields=['started_at'], name='behavioral__started_4ccd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralsession',
            index=models.Index(fields=['session_start_time', 'session_end_time'], name='behavioral__session_6a51e0_idx'),
        ),
    ]
