apiVersion: v1
kind: Secret
metadata:
  name: pymetrics-secret
  namespace: pymetrics
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  SECRET_KEY: "ZGphbmdvLWluc2VjdXJlLTk3M3QoazBjOXBuXzhpcWIya3Vxd3RrMXd0dzdsJT02KzNwZHEzJWQ9aHVeKWEoM20="
  DATABASE_PASSWORD: "cHltZXRyaWNz"
  REDIS_PASSWORD: "cmVkaXNfcGFzc3dvcmQ="
  POSTGRES_PASSWORD: "cHltZXRyaWNz"
stringData:
  # Plain text values for development
  DJANGO_SECRET_KEY: "django-insecure-973t(k0c9pn_8iqb2k%uqwtk1wtw7l%=6+3pdq3%d=hu^)a(3m"
  DATABASE_PASSWORD: "pymetrics"
  REDIS_PASSWORD: "redis_password"
  POSTGRES_PASSWORD: "pymetrics" 