# Generated by Django 5.0.1 on 2025-07-15 02:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('balloon_risk', 'Balloon Risk Game'), ('memory_cards', 'Memory Cards Game'), ('reaction_timer', 'Reaction Timer Game'), ('sorting_task', 'Sorting Task Game'), ('pattern_completion', 'Pattern Completion Game'), ('stroop_test', 'Stroop Test Game'), ('tower_of_hanoi', 'Tower of Hanoi Game'), ('emotional_faces', 'Emotional Faces Game'), ('trust_game', 'Trust Game'), ('stop_signal', 'Stop Signal Game'), ('digit_span', 'Digit Span Game'), ('fairness_game', 'Fairness Game')], max_length=50)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration', models.IntegerField(help_text='Duration in milliseconds')),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('reaction_times', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
            ],
        ),
    ]
