# Generated by Django 5.0.1 on 2025-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('balloon_risk', 'Balloon Risk Game'), ('memory_cards', 'Memory Cards Game'), ('reaction_timer', 'Reaction Timer Game'), ('sorting_task', 'Sorting Task Game'), ('pattern_completion', 'Pattern Completion Game'), ('stroop_test', 'Stroop Test Game'), ('tower_of_hanoi', 'Tower of Hanoi Game'), ('emotional_faces', 'Emotional Faces Game'), ('trust_game', 'Trust Game'), ('stop_signal', 'Stop Signal Game'), ('digit_span', 'Digit Span Game'), ('fairness_game', 'Fairness Game'), ('letters', 'Letters Game'), ('magnitudes', 'Magnitudes Game'), ('sequences', 'Sequences Game')], max_length=50),
        ),
    ]
