# Generated by Django 5.0.1 on 2025-07-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameresult_accuracy_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('abandoned', 'Abandoned')], default='incomplete', help_text='Whether the game was fully completed or abandoned early', max_length=20),
        ),
    ]
