# Generated by Django 5.0.1 on 2025-07-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameresult_completion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdifficultyconfig',
            name='game_type',
            field=models.CharField(choices=[('money_exchange_1', 'Money Exchange Game #1'), ('balloon_risk', 'The Inflation Gambit'), ('memory_cards', 'Cognitive Atlas Challenge'), ('reaction_timer', 'Reaction Timer Game'), ('sorting_task', 'Cognitive Sorting Challenge'), ('pattern_completion', 'Inductive Reasoning Challenge'), ('stroop_test', 'Cognitive Control Challenge'), ('tower_of_hanoi', 'Progressive Planning Task'), ('emotional_faces', 'Facial Emotion Perception'), ('stop_signal', 'Inhibitory Control Challenge'), ('digit_span', 'Working Memory Challenge'), ('fairness_game', 'Economic Fairness Challenge'), ('money_exchange_2', 'The Trust Dilemma'), ('easy_or_hard', 'Cognitive Effort Discounting Task'), ('cards_game', 'Strategic Investment Task'), ('arrows_game', 'Flanker Task'), ('lengths_game', 'Perceptual Acuity Challenge'), ('keypresses', 'Rhythmic Precision Task'), ('faces_game', 'Emotional Recognition Task'), ('letters', 'Cognitive Reflex Test'), ('magnitudes', 'Numerical Acuity Challenge'), ('attention_network', 'Attention Control Challenge')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('money_exchange_1', 'Money Exchange Game #1'), ('balloon_risk', 'The Inflation Gambit'), ('memory_cards', 'Cognitive Atlas Challenge'), ('reaction_timer', 'Reaction Timer Game'), ('sorting_task', 'Cognitive Sorting Challenge'), ('pattern_completion', 'Inductive Reasoning Challenge'), ('stroop_test', 'Cognitive Control Challenge'), ('tower_of_hanoi', 'Progressive Planning Task'), ('emotional_faces', 'Facial Emotion Perception'), ('stop_signal', 'Inhibitory Control Challenge'), ('digit_span', 'Working Memory Challenge'), ('fairness_game', 'Economic Fairness Challenge'), ('money_exchange_2', 'The Trust Dilemma'), ('easy_or_hard', 'Cognitive Effort Discounting Task'), ('cards_game', 'Strategic Investment Task'), ('arrows_game', 'Flanker Task'), ('lengths_game', 'Perceptual Acuity Challenge'), ('keypresses', 'Rhythmic Precision Task'), ('faces_game', 'Emotional Recognition Task'), ('letters', 'Cognitive Reflex Test'), ('magnitudes', 'Numerical Acuity Challenge'), ('attention_network', 'Attention Control Challenge')], max_length=50),
        ),
    ]
